services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
    - HOST=0.0.0.0
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
